#
# Module manifest for module 'Rename-MediaFile'
#
# Generated by: GenChadT
#
# Generated on: 7/19/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Rename-MediaFile.psm1'

# Version number of this module.
ModuleVersion = '0.2.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a048737e-3012-4c04-8bb3-4d9acf8d926a'

# Author of this module
Author = 'GenChadT'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) GenChadT. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Media renaming module for Plex and Jellyfin standards. Renames videos, subtitle sidecars and folders, detects subtitle language, and optionally removes scene junk files.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.6'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Rename-MediaFile'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Rename-MediaFile.psd1'
    'Rename-MediaFile.psm1'
    'Private\_Config.ps1'
    'Private\Format-EpisodeFileName.ps1'
    'Private\Format-MediaTitle.ps1'
    'Private\Format-SubtitleFileName.ps1'
    'Private\Get-JunkFile.ps1'
    'Private\Get-MediaScore.ps1'
    'Private\Get-SubtitleFile.ps1'
    'Private\Get-SubtitleLanguage.ps1'
    'Private\Invoke-RenamePlan.ps1'
    'Private\Read-SubtitleLanguageChoice.ps1'
    'Private\Read-SubtitleSample.ps1'
    'Private\Remove-FileSafely.ps1'
    'Private\Resolve-DirectoryName.ps1'
    'Private\Resolve-EpisodeName.ps1'
    'Private\Resolve-ExtraName.ps1'
    'Private\Resolve-MovieName.ps1'
    'Private\Show-RenamePreview.ps1'
    'Public\Rename-MediaFile.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Plex', 'Jellyfin', 'Media', 'Rename', 'Subtitles', 'Kodi')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
0.2.0
  - Refactored the single monolithic .psm1 into Private\ and Public\ files
    with a thin loader. Helper scriptblocks are now real functions, which
    also removes a latent $Matches clobbering bug in show-name resolution.
  - Added subtitle sidecar support: discovery beside the video and inside
    Subs\ folders, association with the correct video, and renaming to the
    Plex/Jellyfin "<video>.<lang>[.sdh|.forced].srt" convention.
  - Subtitle language detection cascade: filename/folder tokens, then
    encoding-aware content analysis, then an optional interactive prompt.
    Common-but-incorrect codes (cn, jp, gr, cz, dk, se, ua) are corrected.
  - Added -SubtitleLanguageOnly for correcting codes in an already
    organised library without touching any other names.
  - Subtitles in Subs\ are flattened beside the video by default
    (-NoFlattenSubtitleFolders to opt out). .idx/.sub pairs rename atomically.
  - Added opt-in junk file removal (-RemoveJunkFiles) via the Recycle Bin.
    .nfo files are never treated as junk.
  - Replaced the clipping Format-Table preview with a full-width, colour
    coded, paged report.

0.0.1
  - Initial release.
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

