#
# Module manifest for module 'Compress-Video'
#
# Generated by: GenChadT
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Compress-Video.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'b7e4f1a2-6c3d-4e9a-9f1b-2d5e8a7c4f10'

# Author of this module
Author = 'Timothy W. Brown'

# Company or vendor of this module
CompanyName = 'Timothy W. Brown'

# Copyright statement for this module
Copyright = '(c) Timothy W. Brown. Authored with LLM assistance (Anthropic Claude, Google Gemini, DeepSeek). All rights reserved.'

# Description of the functionality provided by this module
Description = 'Batch compresses video files with FFmpeg. Supports auto-detected GPU hardware acceleration (NVENC/QSV/AMF) with CPU (libx265) fallback, ffprobe-based resume/skip detection so interrupted runs never redo finished work, throttled parallel execution with conservative safe defaults, reduced process priority so compression never saturates the machine, and persistent JSON configuration via Get-/Set-CompressVideoConfig.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Compress-Video', 'Get-CompressVideoConfig', 'Set-CompressVideoConfig')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'Compress-Video.psd1'
    'Compress-Video.psm1'
    'Private\_Config.ps1'
    'Private\Build-FFmpegArgs.ps1'
    'Private\Get-CompressionMetrics.ps1'
    'Private\Get-HardwareEncoder.ps1'
    'Private\Get-VideoDuration.ps1'
    'Private\Get-VideoFiles.ps1'
    'Private\Invoke-FFmpegJob.ps1'
    'Private\New-CompressedPath.ps1'
    'Private\Test-CompressedOutput.ps1'
    'Private\Test-FFTools.ps1'
    'Private\Test-OutputPathInternal.ps1'
    'Public\Compress-Video.ps1'
    'Public\Get-CompressVideoConfig.ps1'
    'Public\Set-CompressVideoConfig.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('FFmpeg', 'Video', 'Compression', 'HEVC', 'NVENC', 'QSV', 'AMF', 'Parallel')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/genchadt/Profile_WindowsPS'

        # ReleaseNotes of this module
        ReleaseNotes = @'
1.0.0
  - Converted from standalone Functions\Compress-Video.ps1 script into a
    Public\/Private\ module layout matching the other modules here.
  - Added GPU hardware acceleration support (NVENC/QSV/AMF) with 'Auto'
    detection via ffmpeg -encoders probing, falling back to CPU (libx265)
    if no hardware encoder is compiled in or requested explicitly.
  - Added ffprobe-based resume/skip detection: existing outputs are
    validated by comparing input/output durations within a configurable
    tolerance rather than just checking file existence, so interrupted
    runs never silently redo (or silently trust corrupt) work. Corrupt
    or duration-mismatched outputs are re-encoded (with a warning),
    never silently deleted.
  - Added throttled parallel execution via ForEach-Object -Parallel.
    Defaults to fully sequential (ThrottleLimit=1) for CPU encoding and
    2 for GPU encoding, always overridable via -ThrottleLimit, so the
    module never saturates the machine by default.
  - Every spawned ffmpeg process now runs at a reduced process priority
    (default BelowNormal, configurable) so compression never starves
    the interactive session.
  - Added persistent JSON configuration (Get-/Set-CompressVideoConfig)
    stored at $HOME\.config\Compress-Video\config.json, covering CRF,
    preset, audio settings, hardware acceleration, throttle limit,
    process priority, extensions, and resume tolerance.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
