#
# Module manifest for module 'Optimize-VMX'
#
# Generated by: GenChadT
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Optimize-VMX.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module

GUID = '41c6ab0b-8f28-44d0-ada6-f69c0d4d84d1'

# Author of this module
Author = 'Timothy W. Brown'

# Company or vendor of this module
CompanyName = 'Timothy W. Brown'

# Copyright statement for this module
Copyright = '(c) Timothy W. Brown. Authored with LLM assistance (Anthropic Claude, Google Gemini, DeepSeek). All rights reserved.'

# Description of the functionality provided by this module
Description = 'Optimizes VMware .vmx configuration files for network stability and legacy OS compatibility. Configures optimal network adapters (vmxnet3/e1000/vlance) based on guestOS, pins hardware versions for legacy operating systems, and ensures time synchronization is enabled.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Optimize-VMX')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all files packaged with this module
FileList = @(
    'Optimize-VMX.psd1'
    'Optimize-VMX.psm1'
    'Private\Set-VMXSetting.ps1'
    'Private\Write-Log.ps1'
    'Public\Optimize-VMX.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{
        LicenseUri = 'https://www.apache.org/licenses/LICENSE-2.0'

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('VMware', 'VMX', 'VirtualMachine', 'Workstation', 'vmxnet3', 'LegacyOS')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/genchadt/Profile_WindowsPS'

        # ReleaseNotes of this module
        ReleaseNotes = @'
1.1.0
  - Converted from standalone Functions\Optimize-VMX.ps1 script into a
    Public\/Private\ module layout matching the other modules here.
  - Added SupportsShouldProcess / -WhatIf / -Confirm support around the
    actual file-write action.
  - Adapter "already correct" detection is now anchored to the full line
    (multiline regex) instead of an unanchored substring match, removing
    any theoretical cross-adapter ambiguity (e.g. ethernet1 vs ethernet10).
  - The hardware-pinning rule loop now stops after the first match, so a
    future overlapping pattern cannot queue conflicting virtualHW.version
    changes.
  - Killing a running vmware-vmx process now polls (up to 5s) for the
    process to actually exit instead of a flat 1 second sleep, so file
    locks are more reliably released before files are rewritten.
  - Skipped/aborted (WhatIf) changes are now correctly counted in the
    summary statistics.
  - Added a log message when no .vmx files are found under -Path.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
