@{
    RootModule        = 'ProfileTools.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '3b9f7e2d-4c1a-4f6e-9b2d-8a1c5e7f0d4b'
    Author            = 'Timothy W. Brown'
    CompanyName       = 'Timothy W. Brown'
    Copyright         = '(c) Timothy W. Brown. Authored with LLM assistance (Anthropic Claude, Google Gemini, DeepSeek). All rights reserved.'
    Description       = 'Personal PowerShell toolbox: functions, utilities and static aliases loaded on demand via command autoload.'
    PowerShellVersion = '7.0'

    FunctionsToExport = @(
        # Functions/
        'Get-Activated'
        'Get-WindowsInstallInfo'
        'Invoke-Titus'
        'Restart-Explorer'
        'Set-WinTargetVersion'
        'Update-M365'
        'Update-VsCode'
        # Utilities/Core.ps1
        'Test-CommandExists'
        'Test-GithubConnection'
        'Clear-Clipboard'
        'Edit-Profile'
        'Sync-Profile'
        'Stop-ProcessByName'
        'Show-Uptime'
        'New-Hastebin'
        'Invoke-PeriodicTable'
        'Get-LatestPowerShellVersion'
        'Update-PowerShell'
        'Update-OhMyPoshCache'
        'Update-ZoxideCache'
        # Utilities/FileSystem.ps1
        'Find-File'
        'Find-Text'
        'New-File'
        'Invoke-Explorer'
        'New-Folder'
        'Extract-Archive'
        'Replace-Text'
        # Utilities/Networking.ps1
        'Test-NetSpeed'
        'Show-MyIP'
        # Utilities/Benchmark.ps1
        'Measure-ProfileLoad'
        # Aliases.ps1 one-liners
        'cpy'
        'pst'
        'head'
        'tail'
        'df'
        'gs'
        'ga'
        'gpush'
        'g'
        'gcom'
        'lazyg'
        'docs'
        'dtop'
        'dl'
        'la'
        'll'
        'flushdns'
        'Get-PublicIP'
        'pgrep'
        'sysinfo'
        'export'
        'quit'
        'py'
    )

    AliasesToExport = @(
        'ep'
        'which'
        'clearclipboard'
        'clearclip'
        'clrclip'
        'ff'
        'find'
        'nf'
        'touch'
        'unzip'
        'extract'
        'explore'
        'open'
        'downloads'
        'testsmtp'
        'testmail'
        'checksmtp'
        'myip'
        'getmyip'
        'showmyip'
        'speed'
        'speedtest'
        'up'
        'uptime'
        'instime'
        'installtime'
        'hb'
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
}
